
/**
 **************************************************************************************************
 * @file        bsp_fdacoefs.h
 * @author
 * @version    v0.1.0
 * @date        
 * @brief
 **************************************************************************************************
 * @attention
 *
 **************************************************************************************************
 */
#ifndef _BSP_FDACOEFS_H_
#define _BSP_FDACOEFS_H_

/**
 * @addtogroup    XXX 
 * @{ 
 */
#include "self_def.h"

/**
 * @addtogroup    bsp_fdacoefs_Modules 
 * @{  
 */

/**
 * @defgroup      bsp_fdacoefs_Exported_Macros 
 * @{  
 */


/**
 * @}
 */

/**
 * @defgroup      bsp_fdacoefs_Exported_Constants
 * @{  
 */
 
/*
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 12-Jun-2020 11:59:14

% Coefficient Format: Decimal

% Discrete-Time IIR Filter (real)                           
% -------------------------------                           
% Filter Structure    : Direct-Form I, Second-Order Sections
% Number of Sections  : 2                                   
% Stable              : Yes                                 
% Linear Phase        : No                                  

                                                           
SOS Matrix:                                                 
1  2  1  1  0.60915524768321205  0.48269532170794782        
1  2  1  1  0.44600956632316258  0.085595667014999668       
                                                            
Scale Values:                                               
0.52296264234779                                            
0.38290130833454056        
*/ 

/*

做如下转换：
1.缩放
[ 1 2 1 ] * 0.5229626423478f 
[ 1 2 1 ] * 0.3829013083345f


得到：
[ 0.5229626423478f   2 * 0.5229626423478f    0.5229626423478f]
[ 0.3829013083345f   2 * 0.3829013083345f    0.3829013083345f]

2.舍掉第四列参数
3.将后两列分别乘以-1，即：

[ 0.5229626423478f   2 * 0.5229626423478f    0.5229626423478f  -0.6091552476832f   -0.4826953217079f]
[ 0.3829013083345f   2 * 0.3829013083345f    0.3829013083345f  -0.4460095663232f   -0.085595667015f ]


这样就得到了滤波器系数组了

*/

/**
 * @}
 */
 
/**
 * @defgroup      bsp_fdacoefs_Exported_Types 
 * @{  
 */
typedef struct
{
	uint8_t iir_order ;
	const float *iir_coeffs;
}BSP_IIRFilter_Param_t ;
/**
 * @}
 */

/**
 * @defgroup      bsp_fdacoefs_Exported_Variables 
 * @{  
 */

extern BSP_IIRFilter_Param_t BSP_IIR_4096LowPass1_3K_Param;

extern BSP_IIRFilter_Param_t BSP_IIR_4096BandPass4_1K_Param ;
extern BSP_IIRFilter_Param_t BSP_IIR_4096HighPass10_Param;
/**
 * @}
 */

/**
 * @defgroup      bsp_fdacoefs_Exported_Functions 
 * @{  
 */
 


/**
 * @}
 */

/**
 * @}
 */

/**
 * @}
 */
#endif
