/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
 * Generated on: 11-Jun-2020 11:04:13
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Program Files\MATLAB\R2014a\extern\include\tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
   0.002234891698082, 0.008939566792329,  0.01340935018849, 0.008939566792329,
   0.002234891698082
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -2.692610987017,    2.867399109111,   -1.403484671368,
     0.2644548164435
};
